### ISSUE TITLE
Morning session: Peer-to-peer review

### ISSUE THREAD

**Issue by smunozmo** [jchernandez87/To-Do-List#7]
Hi @jchernandez87 

Good job so far! 

![](https://media4.giphy.com/media/Kzbo6AR9JMf7f15i50/giphy.gif)

Kindly refactor your AddList function to be simpler in order to be tested easily.

Happy coding! 🤓

**Comment by gabrielyea** [comment]
I would suggest you keep in mind the single responsibility principle and try to refactor your functions so they only do 1 thing.
