### ISSUE TITLE
Code review Peer to peer review

### ISSUE THREAD

**Issue by jchernandez87** [jchernandez87/To-Do-List#8]
* This is a code review practice.

![](https://media3.giphy.com/media/jkSvCVEXWlOla/giphy.gif)

**Comment by afcastaneda223** [comment]
all good

**Comment by smunozmo** [comment]
Hi @jchernandez87 

Good job so far! 🚀

Kindly refactor your functions for better testing.

Happy coding! 🤓

**Comment by gabrielyea** [comment]
![](https://media2.giphy.com/media/VFHWGT96hbfsjDJ57S/giphy.gif)
Keep working hard!
